name: Node.js CI

on:
  push:
    branches: [main]
    paths:
      - 'packages/envguard-node/**'
      - '.github/workflows/node.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/envguard-node/**'
      - '.github/workflows/node.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          
      - name: Install dependencies
        working-directory: packages/envguard-node
        run: pnpm install
        
      - name: Lint
        working-directory: packages/envguard-node
        run: pnpm lint
        
      - name: Test
        working-directory: packages/envguard-node
        run: pnpm test
        
      - name: Build
        working-directory: packages/envguard-node
        run: pnpm build 