name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      # Required for OpenID Connect PyPI publishing
      id-token: write
      # Required for creating releases
      contents: write

    defaults:
      run:
        working-directory: ./packages/envguard-python

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Check distribution
      run: |
        python -m twine check dist/*

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        packages-dir: packages/envguard-python/dist/
        skip-existing: true
        verbose: true

    - name: Publish to PyPI
      # Only publish to PyPI on release event
      if: github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: packages/envguard-python/dist/
        verbose: true

    - name: Create GitHub Release
      # Only create release on workflow_dispatch
      if: github.event_name == 'workflow_dispatch'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
